// <auto-generated />
namespace dich.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class films : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(films));
        
        string IMigrationMetadata.Id
        {
            get { return "201810090822154_films"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
